### ISSUE TITLE
Error: VM Exception while processing transaction: reverted with custom error 

### ISSUE THREAD

**Issue by 0xcryptohasher** [ensdomains/offchain-resolver#10]
I see the following error in the logs when I follow the steps in readme and run `yarn start:client --registry 0x5FbDB2315678afecb367f032d93F642f64180aa3 foo.test.eth`. Is the exception expected because L1 cannot find mapping for foo.test.eth?

```
eth_chainId (3)
eth_call
  Contract call:       ENSRegistry#resolver
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3

eth_chainId
eth_call
  Contract call:       ENSRegistry#resolver
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3

eth_chainId
eth_call
  Contract call:       OffchainResolver#resolve
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xe7f1725e7734ce288f8367e1bb143e90bb3f0512

  Error: VM Exception while processing transaction: reverted with custom error 'OffchainLookup("0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512", ["http://localhost:8000/{sender}/{data}.json"], "0x9061b92300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000e03666f6f0474657374036574680000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000243b3b57dea6d6a17bc9cf848dd8cb1b0f45d822b5999459c62a8706fb2f5620572afddf8000000000000000000000000000000000000000000000000000000000", "0xf4d4d2f8", "0x9061b92300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000e03666f6f0474657374036574680000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000243b3b57dea6d6a17bc9cf848dd8cb1b0f45d822b5999459c62a8706fb2f5620572afddf8000000000000000000000000000000000000000000000000000000000")'
      at OffchainResolver.resolve (contracts/OffchainResolver.sol:45)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at HardhatNode.runCall (/Users/test/Downloads/Source/offchain-resolver-main/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:534:20)
      at EthModule._callAction (/Users/test/Downloads/Source/offchain-resolver-main/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:9)
      at HardhatNetworkProvider._sendWithLogging (/Users/test/Downloads/Source/offchain-resolver-main/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:138:22)
      at HardhatNetworkProvider.request (/Users/test/Downloads/Source/offchain-resolver-main/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:115:18)
      at JsonRpcHandler._handleRequest (/Users/test/Downloads/Source/offchain-resolver-main/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at JsonRpcHandler._handleSingleRequest (/Users/test/Downloads/Source/offchain-resolver-main/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)

eth_call
  Contract call:       OffchainResolver#resolveWithProof
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xe7f1725e7734ce288f8367e1bb143e90bb3f0512
```

**Comment by Arachnid** [comment]
This is expected - and not actually an error, just part of how CCIP Read works.
