### ISSUE TITLE
Problem to build the gateway

### ISSUE THREAD

**Issue by andrii-kl** [ensdomains/offchain-resolver#3]
Have an Error in the process of building the gateway.

**I did next commands:** 
cd packages/gateway
yarn && yarn build

**System properties:**
OS: MAC
node: v14.17.4

**Error:**
`
(typescript) Error: /Users/anymac/projects/web3j/offchain-resolver/packages/gateway/src/server.ts(2,45): semantic error TS2307: Cannot find module '@ensdomains/offchain-resolver-contracts/artifacts/contracts/OffchainResolver.sol/IResolverService.json' or its corresponding type declarations.
Error: /Users/anymac/projects/web3j/offchain-resolver/packages/gateway/src/server.ts(2,45): semantic error TS2307: Cannot find module '@ensdomains/offchain-resolver-contracts/artifacts/contracts/OffchainResolver.sol/IResolverService.json' or its corresponding type declarations.
    at error (/Users/anymac/projects/web3j/offchain-resolver/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at throwPluginError (/Users/anymac/projects/web3j/offchain-resolver/node_modules/rollup/dist/shared/node-entry.js:11878:12)
    at Object.error (/Users/anymac/projects/web3j/offchain-resolver/node_modules/rollup/dist/shared/node-entry.js:12912:24)
    at Object.error (/Users/anymac/projects/web3j/offchain-resolver/node_modules/rollup/dist/shared/node-entry.js:12081:38)
    at RollupContext.error (/Users/anymac/projects/web3j/offchain-resolver/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17237:30)
    at /Users/anymac/projects/web3j/offchain-resolver/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25033:23
    at arrayEach (/Users/anymac/projects/web3j/offchain-resolver/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:545:11)
    at Function.forEach (/Users/anymac/projects/web3j/offchain-resolver/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9397:14)
    at printDiagnostics (/Users/anymac/projects/web3j/offchain-resolver/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25006:12)
    at Object.transform (/Users/anymac/projects/web3j/offchain-resolver/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29277:17)

error Command failed with exit code 1.
`

**Comment by alnandr** [comment]
I am experiencing the same error as well:

`(typescript) Error: /home/alnandr/offchain-resolver/packages/gateway/src/server.ts(2,45): semantic error TS2307: Cannot find module '@ensdomains/offchain-resolver-contracts/artifacts/contracts/OffchainResolver.sol/IResolverService.json' or its corresponding type declarations.`

**Comment by Arachnid** [comment]
Please cd into `packages/contracts` and do `yarn build` first. I'll leave this issue open as a reminder to update the build process to build that dependency first.

**Comment by andrii-kl** [comment]
It's working, thanks.
