### ISSUE TITLE
Erorr:  OffchainResolver#resolve 

### ISSUE THREAD

**Issue by andrii-kl** [ensdomains/offchain-resolver#5]
Steps to reproduce: 
1) Run the gateway (following to Readme)
2) Run the contracts (following to Readme)
3) Run the client (following to Readme)
4) In scope of client terminal execute next command:
yarn start --registry 0x5FbDB2315678afecb367f032d93F642f64180aa3 test.eth

In the Gateway terminal we can see next logs:

`eth_chainId (3)
eth_call
  Contract call:       ENSRegistry#resolver
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3

eth_chainId
eth_call
  Contract call:       ENSRegistry#resolver
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3

eth_chainId
eth_call
  Contract call:       OffchainResolver#resolve
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xe7f1725e7734ce288f8367e1bb143e90bb3f0512

  Error: VM Exception while processing transaction: reverted with custom error 'OffchainLookup("0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512", ["http://localhost:8000/{sender}/{data}.json"], "0x9061b92300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000e03666f6f0474657374036574680000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000243b3b57dea6d6a17bc9cf848dd8cb1b0f45d822b5999459c62a8706fb2f5620572afddf8000000000000000000000000000000000000000000000000000000000", "0xf4d4d2f8", "0x9061b92300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000e03666f6f0474657374036574680000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000243b3b57dea6d6a17bc9cf848dd8cb1b0f45d822b5999459c62a8706fb2f5620572afddf8000000000000000000000000000000000000000000000000000000000")'
      at OffchainResolver.resolve (contracts/OffchainResolver.sol:45)
      at HardhatNode._gatherTraces (..../offchain-resolver/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1529:30)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at HardhatNode.runCall (..../offchain-resolver/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:534:31)
      at EthModule._callAction (.../offchain-resolver/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:26)
      at HardhatNetworkProvider._sendWithLogging (..../offchain-resolver/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:138:33)
      at HardhatNetworkProvider.request (..../offchain-resolver/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:115:29)
      at JsonRpcHandler._handleRequest (..../offchain-resolver/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:41)

eth_call
  Contract call:       OffchainResolver#resolveWithProof
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xe7f1725e7734ce288f8367e1bb143e90bb3f0512
`

**Comment by Arachnid** [comment]
This is expected; it's just hardhat network logging the revert message.
