### ISSUE TITLE
NETWORK_ERROR : could not detect network

### ISSUE THREAD

**Issue by 0xcryptohasher** [ensdomains/offchain-resolver#9]
Super helpful readme. Thanks! I ran into an issue at the last step. Any thoughts on what could be the issue?

```
$ yarn start:client --registry 0x5FbDB2315678afecb367f032d93F642f64180aa3 test.eth
yarn run v1.22.17
$ yarn workspace @ensdomains/offchain-resolver-client start --registry 0x5FbDB2315678afecb367f032d93F642f64180aa3 test.eth
$ node dist/index.js --registry 0x5FbDB2315678afecb367f032d93F642f64180aa3 test.eth
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.2)
    at Logger.makeError (/Users/test/Downloads/Source/offchain-resolver-main/node_modules/@ethersproject/logger/lib/index.js:199:21)
    at Logger.throwError (/Users/test/Downloads/Source/offchain-resolver-main/node_modules/@ethersproject/logger/lib/index.js:208:20)
    at JsonRpcProvider.<anonymous> (/Users/test/Downloads/Source/offchain-resolver-main/packages/client/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:517:54)
    at step (/Users/test/Downloads/Source/offchain-resolver-main/packages/client/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/test/Downloads/Source/offchain-resolver-main/packages/client/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/test/Downloads/Source/offchain-resolver-main/packages/client/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```

**Comment by 0xcryptohasher** [comment]
Thanks! This is resolved after I restarted `npx hardhat node`.
